model_name: 'resnet' # 'resnet', 'vit'
data_dir: 'cub' # 'cub', 'dogs', 'air'
batch_size: 64
num_epochs: 10
dropout_rate: 0.5
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.0001
criteria: 'cross_entropy' # 'cross_entropy'
optimizer: 'adam' # 'adam', 'sgd'
scheduler_step_size: 5
scheduler_gamma: 0.1
patience: 3
resize: 256
crop_size: 224
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
freeze_layers_except_last: False
layers_to_freeze: None